const startBtn = document.querySelector("#startButton");
const stopBtn = document.querySelector("#pauseButton");
const resetBtn = document.querySelector("#resetButton");
const progressbar = document.querySelector(".progressbar");
const progressbarNumber = document.querySelector(".progressbar .progressbar-number");
const workPomo = document.getElementById("workPomo");
const sbButton = document.getElementById("sbButton");
const lbButton = document.getElementById("lbButton");
const pomCount = document.querySelector(".pomdoro-count");